# Generated by Django 3.0.6 on 2020-05-25 12:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20200525_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=ckeditor.fields.RichTextField(default='hello'),
            preserve_default=False,
        ),
    ]
