# Generated by Django 3.0.6 on 2020-05-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_post_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=128)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
